name: Build & release cycle

on:
    workflow_dispatch:
    push:
        tags:
            - 'v*'


jobs:
    # Build debugger and debug server for Win32 and Linux64
    build:
      uses: ./.github/workflows/release-gen.yml

    # Attach to github release
    upload:
      needs: build
      runs-on: ubuntu-latest

      steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Prime release (version)
          run: echo "version=$(awk -F'=' '/^VERSION:=/{print $2}' Makefile)" >> $GITHUB_ENV

        - name: Download server artifact
          uses: actions/download-artifact@v4
          with:
            name: v5dbg@${{ env.version }}
        - name: Download debugger (win32)
          uses: actions/download-artifact@v4
          with:
            name: v5dbg_debugger.Windows.X64.zip
        - name: Download debugger (linux)
          uses: actions/download-artifact@v4
          with:
            name: v5dbg_debugger.Linux.X64
        - name: Make GitHub release
          uses: softprops/action-gh-release@v2
          with:
            make_latest: true
            files: |
              v5dbg_debugger.Windows.X64
              v5dbg_debugger.Linux.X64
              v5dbg@${{ env.version }}

    depot:
      permissions:
        # permits reading of releases and writing to the depot branch
        contents: write
      needs: upload
      uses: ./.github/workflows/depot.yml
