name: Build & release cycle

on:
    workflow_dispatch:
    push:
        tags:
            - 'v*'


jobs:
    # Build debugger and debug server for Win32 and Linux64
    build:
      uses: ./.github/workflows/release-gen.yml

    # Attach to github release
    upload:
      needs: build
      runs-on: ubuntu-latest

      permissions:
        contents: write

      steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Prime release (version)
          run: echo "version=$(awk -F'=' '/^VERSION:=/{print $2}' Makefile)" >> $GITHUB_ENV

        - name: Download artifacts
          uses: actions/download-artifact@v4

        - name: Zip Win32
          run: zip -r ../v5dbg_debugger.Windows.X64.zip *
          working-directory: v5dbg_debugger.Windows.X64

        - name: Zip Linux
          run: zip -r ../v5dbg_debugger.Linux.X64.zip .
          working-directory: v5dbg_debugger.Linux.X64

        - name: Zip server
          run: zip -r ../v5dbg@${{ env.version }}.zip .
          working-directory: v5dbg@${{ env.version }}

        - name: Debug list
          run: ls -al

        - name: Make GitHub release
          uses: softprops/action-gh-release@v2
          with:
            make_latest: true
            files: |
              v5dbg_debugger.Windows.X64.zip
              v5dbg_debugger.Linux.X64.zip
              v5dbg@${{ env.version }}.zip

    depot:
      permissions:
        # permits reading of releases and writing to the depot branch
        contents: write
      needs: upload
      uses: ./.github/workflows/depot.yml
