name: "Generate build artifacts for release"

on:
    release:
    workflow_dispatch:

jobs:
    debugger:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.14.0"

            - name: Install rust
              uses: actions-rust-lang/setup-rust-toolchain@v1
            
            - name: Install dependencies (Rust)
              run: sudo apt install libdbus-1-dev pkg-config
            
            - name: Build comms server
              run: cargo build --release
              working-directory: v5dbg-server

            - name: Install dependencies (Python)
              run: pip install pygments prompt_toolkit pyinstaller
            
            - name: Run build
              run: python3 integration/ci.py client
              working-directory: v5dbg-server

            - name: Extract build
              run: unzip v5dbg_debugger.zip -d v5dbg_debugger

            - name: Upload release
              uses: actions/upload-artifact@v4
              with:
                  name: v5dbg_debugger__${{ runner.os }}
                  path: v5dbg_debugger/*

    server:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.14.0"

            - name: Download compiler toolchain
              run: curl -#L "https://developer.arm.com/-/media/Files/downloads/gnu/13.3.rel1/binrel/arm-gnu-toolchain-13.3.rel1-x86_64-arm-none-eabi.tar.xz" -O

            - name: Extract compiler toolchain
              run: tar -xvf arm-gnu-toolchain-13.3.rel1-x86_64-arm-none-eabi.tar.xz

            - name: Install PROS cli
              run: pip3 install pros-cli

            - name: Build template
              run: /bin/bash -c "export PATH=$PATH:$PWD/arm-gnu-toolchain-13.3.rel1-x86_64-arm-none-eabi/bin; make template -j"

            - name: Extract template
              run: unzip v5dbg*.zip -d template

            - name: Prime release (name)
              run: echo "library_name=$(awk -F'=' '/^LIBNAME:=/{print $2}' Makefile)" >> $GITHUB_ENV

            - name: Prime release (version)
              run: echo "version=$(awk -F'=' '/^VERSION:=/{print $2}' Makefile)" >> $GITHUB_ENV

            - name: Upload release
              uses: actions/upload-artifact@v4
              with:
                  name: ${{ env.library_name }}@${{ env.version }}
                  path: ${{ github.workspace }}/template
